version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/source/rxinvoice-master
hooks:
    BeforeInstall:
    - location: scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: start.sh
      runas: root
 
