version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/restx
hooks:
   BeforeInstall:
   - location: scripts/startapache.sh
      runas: root
   AfterInstall:
   - location: start.sh
      runas: root
