version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/source/rxinvoice-master
hooks:
   AfterInstall:
    - location: /home/ubuntu/source/rxinvoice-master/start.sh
      runas: root