version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/restx
hooks:
   BeforeInstall:
    - location: scripts/startapache.sh
      timeout: 300
      runas: root
   AfterInstall:
    - location: nohup sh start.sh &
      timeout: 300
      runas: root
